FROM python:3

WORKDIR /build-usb

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

EXPOSE 8942

COPY . .

CMD ["python3", "./src/riots-usb.py"]
