name: riots-webthings-actions

on:
  push:
    branches: [ "master"]
    tags:
      - 'v*.*.*'

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub container registry (ghcr.io)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Riots Usb
      uses: docker/build-push-action@v4
      with:        
        file: Dockerfile.usb
        push: true
        tags: ghcr.io/sifis-home/sifis-home/riots-usb:latest

    - name: Build and push Riots Webthings
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.webthings
        push: true
        tags: ghcr.io/sifis-home/sifis-home/riots-webthings:latest

    - name: Build and push Riots DHT
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.dht
        push: true
        tags: ghcr.io/sifis-home/sifis-home/riots-dht:latest
